
const bank=window.QUESTION_BANK;let mode='exam',quiz=[],idx=0,correct=0,answered=false,mistakes=[],timerId=null,timeLeft=0;
const $=id=>document.getElementById(id),shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
[...new Set(bank.map(x=>x.category))].sort().forEach(t=>$('topic').insertAdjacentHTML('beforeend',`<option>${t}</option>`));
function updateHome(){$('best').textContent=load('apro_best',null)?.percent?load('apro_best').percent+'%':'—';$('saved').textContent=load('apro_errors',[]).length}updateHome();
document.querySelectorAll('.modebtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.modebtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode});
$('themeBtn').onclick=()=>{const dark=document.body.classList.toggle('dark');document.body.classList.toggle('light',!dark);save('apro_theme',dark?'dark':'light')};document.body.classList.add(load('apro_theme','light'));
function distractors(item){let pool=bank.filter(x=>x.id!==item.id&&x.category===item.category&&x.answer!==item.answer);if(pool.length<3)pool=bank.filter(x=>x.id!==item.id&&x.answer!==item.answer);return shuffle([...pool]).slice(0,3).map(x=>x.answer)}
function prepare(arr){return arr.map(x=>({...x,options:shuffle([x.answer,...distractors(x)])}))}
$('startBtn').onclick=()=>{let pool=[...bank],topic=$('topic').value;if(topic!=='all')pool=pool.filter(x=>x.category===topic);if(mode==='mistakes'){const ids=load('apro_errors',[]);pool=pool.filter(x=>ids.includes(x.id));if(!pool.length)return alert('Zatím nejsou uložené žádné chyby.')}let n=Math.min(+$('count').value,pool.length);quiz=prepare(shuffle(pool).slice(0,n));idx=0;correct=0;mistakes=[];timeLeft=+$('time').value*60;$('home').classList.add('hidden');$('quiz').classList.remove('hidden');startTimer();render()};
function startTimer(){clearInterval(timerId);if(!timeLeft){$('timer').textContent='';return}tick();timerId=setInterval(()=>{timeLeft--;tick();if(timeLeft<=0){clearInterval(timerId);finish()}},1000)}
function tick(){$('timer').textContent=`${String(Math.floor(timeLeft/60)).padStart(2,'0')}:${String(timeLeft%60).padStart(2,'0')}`}
function render(){answered=false;let q=quiz[idx];$('counter').textContent=`Otázka ${idx+1} / ${quiz.length}`;$('bar').style.width=`${idx/quiz.length*100}%`;$('tag').textContent=q.category;$('question').textContent=q.question;$('feedback').textContent='';$('source').classList.add('hidden');$('nextBtn').disabled=true;$('options').innerHTML='';q.options.forEach(opt=>{let b=document.createElement('button');b.className='option';b.textContent=opt;b.onclick=()=>choose(b,opt);$('options').appendChild(b)})}
function choose(btn,opt){if(answered)return;answered=true;let q=quiz[idx],ok=opt===q.answer;if(ok)correct++;else mistakes.push(q);document.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(b.textContent===q.answer)b.classList.add('correct');else if(b===btn)b.classList.add('wrong')});if(mode==='learn'){let f=$('feedback');f.textContent=ok?'Správně!':'Nesprávně. Správná odpověď je zeleně.';f.className='feedback '+(ok?'ok':'bad');$('source').textContent='Původní formulace: '+q.source;$('source').classList.remove('hidden')}$('nextBtn').disabled=false}
$('nextBtn').onclick=()=>idx<quiz.length-1?(idx++,render()):finish();$('quitBtn').onclick=()=>confirm('Ukončit test?')&&finish();
function finish(){clearInterval(timerId);if(!quiz.length)return;$('quiz').classList.add('hidden');$('result').classList.remove('hidden');let pct=Math.round(correct/quiz.length*100);$('score').textContent=`${correct}/${quiz.length}`;$('percent').textContent=pct+'%';$('wrong').textContent=mistakes.length;$('grade').textContent=pct>=80?'Výborně':pct>=60?'Dobře':'Procvičit';let ids=[...new Set([...load('apro_errors',[]),...mistakes.map(x=>x.id)])];save('apro_errors',ids);let best=load('apro_best',null);if(!best||pct>best.percent)save('apro_best',{percent:pct,date:new Date().toISOString()});$('review').innerHTML=mistakes.length?'<h3>Chybné odpovědi</h3>'+mistakes.map(x=>`<div class="reviewitem"><b>${esc(x.question)}</b><br><span class="ok">${esc(x.answer)}</span></div>`).join(''):'<p class="ok"><b>Bez chyb.</b></p>';updateHome()}
const esc=s=>s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
$('againBtn').onclick=()=>location.reload();$('retryBtn').onclick=()=>{if(!mistakes.length)return alert('V tomto testu nebyly chyby.');quiz=prepare(shuffle([...mistakes]));idx=0;correct=0;mistakes=[];$('result').classList.add('hidden');$('quiz').classList.remove('hidden');render()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
